name: myenv # This will become the name of your environment
dependencies: # The list of packages to include in your environment
    - python=3.9 # You can specify versions
    - pip # Install pip in your environment
    - pip: # Include pip dependencies last
        - awscli
        - alembic
        - click
        - dcmrtstruct2nii
        - git+https://github.com/Dutta-SD/nnunet_draw.git@draw_main
        - nibabel
        - numpy
        - pandas
        - pydicom
        - PyYAML
        - retry
        - rt-utils
        - schema
        - simpleitk
        - sqlalchemy
        - boto3
        - torch==2.0.0
        - torchaudio
        - torchvision
        - watchdog    

