name: Build Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!.github/**'

# This job builds and pushes the Docker image
jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    # No special permissions needed since we're not pushing
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.10.0

      - name: Set up build metadata
        id: meta
        run: |
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "ref=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: local-build:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            UID=1001
            GID=1001

      - name: Build info
        run: |
          echo "Build completed successfully"
          echo "Commit: ${{ steps.meta.outputs.sha }}"
          echo "Branch/Ref: ${{ steps.meta.outputs.ref }}"
